# Generated by Django 5.1.1 on 2024-09-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensao', models.CharField(max_length=10, verbose_name='Extensão')),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('perfil', models.BooleanField(verbose_name='Perfil do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(max_length=255, verbose_name='Arquivo')),
                ('data_feedback', models.DateField(verbose_name='Data do Feedback')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuário')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('tamanho', models.FloatField(verbose_name='Tamanho')),
                ('data_conversao', models.DateField(verbose_name='Data')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('fconvertido', models.CharField(max_length=10, verbose_name='Formato Convertido')),
                ('foriginal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formato', verbose_name='Formato Original')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuário')),
            ],
            options={
                'verbose_name': 'Conversão',
                'verbose_name_plural': 'Conversões',
            },
        ),
    ]
