# Generated by Django 5.1.1 on 2024-09-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='app/static/files')),
            ],
        ),
        migrations.AlterField(
            model_name='conversao',
            name='nome_arquivo',
            field=models.CharField(max_length=255, verbose_name='Nome do Arquivo'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mensagem',
            field=models.TextField(max_length=255, verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='conversao',
            name='arquivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.arquivo', verbose_name='Arquivo'),
        ),
    ]
