# Generated by Django 5.1.1 on 2024-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_arquivo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AddField(
            model_name='arquivo',
            name='tempo',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
