# Generated by Django 5.1.1 on 2024-09-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_conversao_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='chave',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tempo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
