# Generated by Django 5.1.2 on 2024-10-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_arquivo_docx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.BooleanField(default=False, verbose_name='Perfil do usuário'),
        ),
    ]
