# Generated by Django 5.1.2 on 2024-12-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_arquivo_usuario_alter_conversao_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='avaliacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Avaliação (Estrelas)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resposta',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta do Administrador'),
        ),
    ]
