# Generated by Django 5.1.2 on 2024-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_arquivo_convertido_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='categoria',
            field=models.CharField(choices=[('Documentos', 'Documentos'), ('Imagens', 'Imagens'), ('Planilhas', 'Planilhas'), ('Vídeos', 'Vídeos')], default='Documentos', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
