# Generated by Django 5.1.2 on 2024-12-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_formato_categoria_alter_arquivo_arquivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversao',
        ),
    ]
